version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '22:22'
    volumes:
      - .data:/var/lib/postgresql/data
    entrypoint:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
